create schema if not exists hotel;

CREATE TABLE  IF NOT EXISTS hotel."ROOM"(
      "ID" UUID PRIMARY KEY
    , "NUMBER" VARCHAR(10000) NOT NULL
    , "NAME" VARCHAR(100) NOT NULL
        , "CAPACITY" INT NOT NULL
    , "LOCATION" VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS hotel."RESERVATION"(
     "ID" UUID PRIMARY KEY
    , "ROOM_ID" UUID NOT NULL
    , "ESTIMATED_CHECKOUT" TIMESTAMP NOT NULL
    , "ESTIMATED_CHECKIN" TIMESTAMP NOT NULL
    , "CHECKOUT" TIMESTAMP NULL
    , "CHECKIN" TIMESTAMP NULL
    , "CLIENT_CPF" VARCHAR(11)  NOT NULL
    , CONSTRAINT "FK_ROOM" FOREIGN KEY("ROOM_ID") REFERENCES hotel."ROOM"("ID")
);
